### ISSUE TITLE
movies not found

### ISSUE THREAD

**Issue by RedcoatAsher** [MartijnOud/IMDb-Bot#1]
> slackbot Darn – that slash command didn't work. Feel free to give it another go, or you can manage the integration (and view who installed it) at IMDb

I am getting this msg when a lookup Die Hard by typing
`/imdb die hard`

**Comment by MartijnOud** [comment]
Unfortunately this has to do with the OMDb API. It seems they are struggling with uptime:

http://omdbapi.com/?t=die+hard

It either times-out or takes too long to load. The creator is [raising money on Patreon](https://www.patreon.com/omdb) and seems to be close to covering the monthly server costs so it should hopefully improve soon.
